version: '3'

services:
    nodejs-app:
        build:
          context: ./server
        container_name: nestserver
        hostname: nestserver
        ports:
            - "8888:8000" 
        networks:
            - example-net  
    nginx:
        build:
          context: ./nginx
        container_name: nginx
        hostname: nginx
        ports:
            - "80:80" 
        depends_on:
            - nodejs-app
        networks:
            - example-net

networks:
  example-net:
    external: true