import Navbar from "./Navbar";
import Script from "next/script";
import styles from "../styles/Home.module.css";
import Head from "next/head";

const Layout = ({children}) => {
    return(

        <div>
            {/* eslint-disable-next-line @next/next/no-script-component-in-head */}
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
                <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
                <Script id="ion-icons" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"/>
                <script noModule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
                <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
            </Head>
            <Navbar />
            {children}
            <footer className={styles.footer}>
                <ul className="flex container flex-wrap text-xl text-text-gray">
                    <li>
                        <a href="https://www.facebook.com/">Facebook</a>
                    </li>
                    <li className="ml-8">
                        <a href="https://www.whatsapp.com/?lang=ru">WhatsApp</a>
                    </li>
                    <li className="ml-8">
                        <a href="https://web.telegram.org/k/">Telegram</a>
                    </li>
                </ul>
            </footer>
        </div>
    )
}
export default Layout